version: '3.8'
services:
  api:
    build: .
    ports:
      - "9876:9876"
    env_file:
      - .env

  # db:
  #   image: postgres:latest
  #   env_file:
  #     - .env
  #   ports:
  #     - "5432:5432"